plank:
 job_url_template: 'https://k8s-gubernator.appspot.com/build/main-nucleus-128012/{{if eq .Spec.Type "presubmit"}}pr-logs/pull/{{.Spec.Refs.Org}}_{{.Spec.Refs.Repo}}/{{with index .Spec.Refs.Pulls 0}}{{.Number}}{{end}}{{else if eq .Spec.Type "batch"}}pr-logs/pull/batch{{else}}logs{{end}}/{{.Spec.Job}}/{{.Status.BuildID}}/'
 report_template: '[Full PR test history](https://k8s-gubernator.appspot.com/pr/{{.Spec.Refs.Org}}_{{.Spec.Refs.Repo}}/{{with index .Spec.Refs.Pulls 0}}{{.Number}}{{end}}). [Your PR dashboard](https://k8s-gubernator.appspot.com/pr/{{with index .Spec.Refs.Pulls 0}}{{.Author}}{{end}}).'

sinker:
 resync_period: 1h
 max_prowjob_age: 48h
 max_pod_age: 12h

prowjob_namespace: default
pod_namespace: test-pods

triggers:
- repos:
  - collabora-gce/compute-image-tools
  trusted_org: collabora-gce

presubmits:
 collabora-gce/compute-image-tools:
 - name: presubmit-unittests
   agent: kubernetes
   always_run: true
   trigger: "(?m)^/unittests$"
   rerun_command: "/unittests"
   context: prow/presubmit/unittests
   spec:
    containers:
    - image: gcr.io/main-nucleus-128012/unittests:latest
      volumeMounts:
      - name: codecov
        mountPath: /etc/codecov
        readOnly: true
      - name: main-nucleus-128012-service-account
        mountPath: /etc/main-nucleus-128012-service-account
        readOnly: true
    volumes:
    - name: codecov
      secret:
       secretName: codecov
    - name: main-nucleus-128012-service-account
      secret:
       secretName: main-nucleus-128012-service-account
 - name: presubmit-gocheck
   agent: kubernetes
   always_run: true
   run_if_changed: ".*\\.go$"
   trigger: "(?m)^/gocheck$"
   rerun_command: "/gocheck"
   context: prow/presubmit/gocheck
   spec:
    containers:
    - image: gcr.io/main-nucleus-128012/gocheck:latest
      volumeMounts:
      - name: main-nucleus-128012-service-account
        mountPath: /etc/main-nucleus-128012-service-account
        readOnly: true
    volumes:
    - name: main-nucleus-128012-service-account
      secret:
       secretName: main-nucleus-128012-service-account
 - name: presubmit-flake8
   agent: kubernetes
   always_run: true
   run_if_changed: ".*\\.py$"
   trigger: "(?m)^/flake8$"
   rerun_command: "/flake8"
   context: prow/presubmit/flake8
   spec:
    containers:
    - image: gcr.io/main-nucleus-128012/flake8:latest
      volumeMounts:
      - name: main-nucleus-128012-service-account
        mountPath: /etc/main-nucleus-128012-service-account
        readOnly: true
    volumes:
    - name: main-nucleus-128012-service-account
      secret:
       secretName: main-nucleus-128012-service-account
 - name: presubmit-gobuild
   agent: kubernetes
   always_run: true
   run_if_changed: ".*\\.go$"
   trigger: "(?m)^/gobuild$"
   rerun_command: "/gobuild"
   context: prow/presubmit/gobuild
   spec:
    containers:
    - image: gcr.io/main-nucleus-128012/gobuild:latest
      volumeMounts:
      - name: main-nucleus-128012-service-account
        mountPath: /etc/main-nucleus-128012-service-account
        readOnly: true
    volumes:
    - name: main-nucleus-128012-service-account
      secret:
       secretName: main-nucleus-128012-service-account

periodics:
- interval: 1m
  agent: kubernetes
  name: echo-test
  spec:
    containers:
    - image: alpine
      command: ["/bin/date"]
 - interval: 6h
   agent: kubernetes
   name: ci-daisy-e2e
   spec:
    containers:
    - image: gcr.io/main-nucleus-128012/daisy-e2e:latest
      args:
      - "--tests=e2e_tests"
      env:
      - name: REPO_OWNER
        value: collabora-gce
      - name: REPO_NAME
        value: compute-image-tools
      volumeMounts:
      - name: main-nucleus-128012-service-account
        mountPath: /etc/main-nucleus-128012-service-account
        readOnly: true
    volumes:
    - name: main-nucleus-128012-service-account
      secret:
       secretName: main-nucleus-128012-service-account
